In [50]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
data=pd.read_csv("customers_data.csv")
data=pd.DataFrame(data)
print(data)

      Customer_ID   Name   Age  Gender       City    Income  Spending_Score  \
0            1001  Rahul  41.0    Male      Delhi   99579.0            99.0
1            1002  Priya  55.0  Female  Bangalore   15255.0            44.0
2            1003   Neha  45.0  Female      Delhi   16502.0            51.0
3            1004   Aman  38.0  Female    Kolkata   85192.0            19.0
4            1005  Rahul  35.0  Female    Kolkata   80424.0             NaN
...           ...    ...   ...     ...        ...       ...             ...
3045         1085   Neha  58.0  Female  Bangalore  421950.0             9.0
3046         1290  Arjun  31.0  Female     Mumbai   49948.0            98.0
3047         3016   Aman  52.0    Male  Bangalore   90583.0            90.0
3048         2409  Karan  57.0  Female  Bangalore   55910.0            14.0
3049         3607   Riya   NaN  Female      Delhi   67474.0            79.0

     Purchased
0          Yes
1          Yes
2          Yes
3          Yes
4           No
...        ...
3045       Yes
3046       Yes
3047        No
3048       Yes
3049        No

[3050 rows x 8 columns]

In [51]:
print(type(data))

<class 'pandas.core.frame.DataFrame'>

In [52]:
data.head()

,Customer_ID,Name,Age,Gender,City,Income,Spending_Score,Purchased
0,1001,Rahul,41.0,Male,Delhi,99579.0,99.0,Yes
1,1002,Priya,55.0,Female,Bangalore,15255.0,44.0,Yes
2,1003,Neha,45.0,Female,Delhi,16502.0,51.0,Yes
3,1004,Aman,38.0,Female,Kolkata,85192.0,19.0,Yes
4,1005,Rahul,35.0,Female,Kolkata,80424.0,NaN,No

In [53]:
data.tail()
data.tail(3)

,Customer_ID,Name,Age,Gender,City,Income,Spending_Score,Purchased
3047,3016,Aman,52.0,Male,Bangalore,90583.0,90.0,No
3048,2409,Karan,57.0,Female,Bangalore,55910.0,14.0,Yes
3049,3607,Riya,NaN,Female,Delhi,67474.0,79.0,No

In [54]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3050 entries, 0 to 3049
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Customer_ID     3050 non-null   int64
 1   Name            3050 non-null   object
 2   Age             2896 non-null   float64
 3   Gender          3050 non-null   object
 4   City            2897 non-null   object
 5   Income          2897 non-null   float64
 6   Spending_Score  2899 non-null   float64
 7   Purchased       3050 non-null   object
dtypes: float64(3), int64(1), object(4)
memory usage: 190.8+ KB

In [55]:
data.sample()

,Customer_ID,Name,Age,Gender,City,Income,Spending_Score,Purchased
1333,2334,Priya,20.0,Female,Kolkata,NaN,60.0,No

In [56]:
data.describe()

       Customer_ID          Age         Income  Spending_Score
count  3050.000000  2896.000000    2897.000000     2899.000000
mean   2501.971803    38.573895   60570.926821       49.411176
std     865.955930    11.897028   57280.117599       28.829117
min    1001.000000    18.000000   15005.000000        1.000000
25%    1752.250000    29.000000   34622.000000       24.000000
50%    2502.500000    39.000000   57287.000000       50.000000
75%    3252.750000    49.000000   78226.000000       74.000000
max    4000.000000    59.000000  960080.000000       99.000000

In [57]:
data.shape

(3050, 8)

In [58]:
data.isnull()

,Customer_ID,Name,Age,Gender,City,Income,Spending_Score,Purchased
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...
3045,False,False,False,False,False,False,False,False
3046,False,False,False,False,False,False,False,False
3047,False,False,False,False,False,False,False,False
3048,False,False,False,False,False,False,False,False
3049,False,False,True,False,False,False,False,False

In [59]:
data.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
3045    False
3046     True
3047     True
3048     True
3049     True
Length: 3050, dtype: bool

In [60]:
data.sort_values(by="Income",ascending=True)

,Customer_ID,Name,Age,Gender,City,Income,Spending_Score,Purchased
2330,3331,Vikas,20.0,Male,Kolkata,15005.0,35.0,Yes
1083,2084,Arjun,40.0,Female,Lucknow,15015.0,39.0,Yes
2541,3542,Neha,39.0,Female,Delhi,15026.0,37.0,No
1671,2672,Riya,49.0,Male,Kolkata,15045.0,52.0,Yes
1038,2039,Aman,55.0,Female,Bangalore,15048.0,15.0,No
...,...,...,...,...,...,...,...,...
2978,3979,Simran,46.0,Female,Mumbai,NaN,43.0,No
2981,3982,Priya,24.0,Male,Lucknow,NaN,3.0,No
3011,2925,Priya,19.0,Female,Kolkata,NaN,50.0,No
3014,1550,Aman,NaN,Male,Mumbai,NaN,86.0,No
3019,1860,Simran,NaN,Female,Lucknow,NaN,98.0,No

In [61]:
data.isnull().sum()

Customer_ID         0
Name                0
Age               154
Gender              0
City              153
Income            153
Spending_Score    151
Purchased           0
dtype: int64

In [62]:
data.duplicated().sum()

np.int64(48)

In [63]:
data["Age"].fillna(data["Age"].median(),inplace=True)
data["Income"].fillna(data["Income"].median())
data["Spending_Score"].fillna(data["Spending_Score"].median())
data["City"].fillna(data["City"].mode()[0])
print(data)

      Customer_ID   Name   Age  Gender       City    Income  Spending_Score  \
0            1001  Rahul  41.0    Male      Delhi   99579.0            99.0
1            1002  Priya  55.0  Female  Bangalore   15255.0            44.0
2            1003   Neha  45.0  Female      Delhi   16502.0            51.0
3            1004   Aman  38.0  Female    Kolkata   85192.0            19.0
4            1005  Rahul  35.0  Female    Kolkata   80424.0             NaN
...           ...    ...   ...     ...        ...       ...             ...
3045         1085   Neha  58.0  Female  Bangalore  421950.0             9.0
3046         1290  Arjun  31.0  Female     Mumbai   49948.0            98.0
3047         3016   Aman  52.0    Male  Bangalore   90583.0            90.0
3048         2409  Karan  57.0  Female  Bangalore   55910.0            14.0
3049         3607   Riya  39.0  Female      Delhi   67474.0            79.0

     Purchased
0          Yes
1          Yes
2          Yes
3          Yes
4           No
...        ...
3045       Yes
3046       Yes
3047        No
3048       Yes
3049        No

[3050 rows x 8 columns]

C:\Users\manas\AppData\Local\Temp\ipykernel_61776\2434973497.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["Age"].fillna(data["Age"].median(),inplace=True)

In [64]:
print(data["City"].mode())
print(data["Gender"].mode())

0    Lucknow
Name: City, dtype: object
0    Female
Name: Gender, dtype: object

In [65]:
data["Gender"].fillna(data["Gender"].mode(),inplace=True)
data["City"].fillna(data["City"].mode(),inplace=True)
print(data)

      Customer_ID   Name   Age  Gender       City    Income  Spending_Score  \
0            1001  Rahul  41.0    Male      Delhi   99579.0            99.0
1            1002  Priya  55.0  Female  Bangalore   15255.0            44.0
2            1003   Neha  45.0  Female      Delhi   16502.0            51.0
3            1004   Aman  38.0  Female    Kolkata   85192.0            19.0
4            1005  Rahul  35.0  Female    Kolkata   80424.0             NaN
...           ...    ...   ...     ...        ...       ...             ...
3045         1085   Neha  58.0  Female  Bangalore  421950.0             9.0
3046         1290  Arjun  31.0  Female     Mumbai   49948.0            98.0
3047         3016   Aman  52.0    Male  Bangalore   90583.0            90.0
3048         2409  Karan  57.0  Female  Bangalore   55910.0            14.0
3049         3607   Riya  39.0  Female      Delhi   67474.0            79.0

     Purchased
0          Yes
1          Yes
2          Yes
3          Yes
4           No
...        ...
3045       Yes
3046       Yes
3047        No
3048       Yes
3049        No

[3050 rows x 8 columns]

C:\Users\manas\AppData\Local\Temp\ipykernel_61776\3590617018.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["Gender"].fillna(data["Gender"].mode(),inplace=True)
C:\Users\manas\AppData\Local\Temp\ipykernel_61776\3590617018.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["City"].fillna(data["City"].mode(),inplace=True)

In [66]:
data.drop_duplicates(inplace=True)

In [67]:
data.sort_values(by="Income",ascending=True)

,Customer_ID,Name,Age,Gender,City,Income,Spending_Score,Purchased
2330,3331,Vikas,20.0,Male,Kolkata,15005.0,35.0,Yes
1083,2084,Arjun,40.0,Female,Lucknow,15015.0,39.0,Yes
2541,3542,Neha,39.0,Female,Delhi,15026.0,37.0,No
1671,2672,Riya,49.0,Male,Kolkata,15045.0,52.0,Yes
1038,2039,Aman,55.0,Female,Bangalore,15048.0,15.0,No
...,...,...,...,...,...,...,...,...
2930,3931,Rahul,44.0,Male,Mumbai,NaN,52.0,No
2958,3959,Aman,23.0,Female,Delhi,NaN,1.0,Yes
2967,3968,Rahul,51.0,Female,Lucknow,NaN,34.0,Yes
2978,3979,Simran,46.0,Female,Mumbai,NaN,43.0,No
2981,3982,Priya,24.0,Male,Lucknow,NaN,3.0,No

In [68]:
Q1=data["Spending_Score"].quantile(0.25)
Q3=data["Spending_Score"].quantile(0.75)
IQR=Q3-Q1

print(Q1,Q3,IQR)

24.0 74.0 50.0

In [69]:
data=(data['Income']>Q1-1.5*IQR)&(data['Income']<Q3+1.5*IQR)
print(data)

0       False
1       False
2       False
3       False
4       False
        ...
2997    False
2998    False
2999    False
3029    False
3045    False
Name: Income, Length: 3002, dtype: bool

In [70]:
data=pd.get_dummies(data,columns=["City"],drop_first=True,dtype=int)
print(data)
data.head()

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[3002 rows x 0 columns]

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

In [71]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
data['Gender']=le.fit_transform(data['Gender'])
data.head()

KeyError: 'Gender'

In [ ]:
from sklearn.preprocessing import StandardScaler
st=StandardScaler()
data[['Age']]=st.fit_transform(data[['Age']])
data[['Income']]=st.fit_transform(data[['Income']])
data.head()

In [ ]:
plt.scatter(data["Income"],data["Purchased"])

In [ ]:
plt.scatter(data["Income"],data["Spending_Score"])

In [ ]:
plt.scatter(data["Spending_Score"],data["Purchased"])